# Generated by Django 4.2.30 on 2026-07-30 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, help_text='Extracted OTP. Null if extraction failed.', max_length=255, null=True, verbose_name='OTP')),
                ('sender', models.CharField(max_length=255, verbose_name='Sender')),
                ('receiver_number', models.CharField(max_length=255, verbose_name='Receiver Number')),
                ('message_body', models.TextField(verbose_name='Message Body')),
                ('received_at', models.DateTimeField(verbose_name='Received At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON metadata for future fields from Android without schema changes.', verbose_name='Metadata')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='The original raw JSON payload received from the Android device.', verbose_name='Raw Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'OTP Message',
                'verbose_name_plural': 'OTP Messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
